### ISSUE TITLE
关于文章与用户的介绍字段

### ISSUE THREAD

**Issue by hanerx** [guateam/Intelligent-annotation-system#10]
**添加功能的初衷（问题）**
由于前端页面需要一段介绍，故请求添加新的字段
![image](https://user-images.githubusercontent.com/31791623/46610734-22f9b080-cb3e-11e8-966a-23898b3ed5cf.png)
![image](https://user-images.githubusercontent.com/31791623/46610740-2e4cdc00-cb3e-11e8-851b-e84b87a78370.png)

**推荐解决方案**
添加新字段

**备用解决方案**
添加新表

**邪道解决方案**
删掉出问题的介绍

**Comment by hanerx** [comment]
用户头像字段也没有

**Comment by laipz8200** [comment]
我晚上加吧

发自我的 iPhone

**Comment by laipz8200** [comment]
已在user表中添加intro字段和avatar_path字段
