### ISSUE TITLE
关于推荐用户的讨论

### ISSUE THREAD

**Issue by hanerx** [guateam/Intelligent-annotation-system#11]
**添加功能的初衷（问题）**
主页需要推荐优秀教师与优秀学生，需要进行讨论

**Comment by hanerx** [comment]
现在有个想法是学生推荐直接用UserCF算法推荐兴趣相似的用户，然后进行推荐。
但是这里有个问题就是推荐的到底要兴趣相似的学生还是只要批注写的好的学生，或者是我全都要系列。

**Comment by laipz8200** [comment]
都要，然后批注写得好的优先

发自我的 iPhone

**Comment by hanerx** [comment]
行吧
![image](https://user-images.githubusercontent.com/31791623/46741855-6ee05d00-ccd8-11e8-9c94-527358468efc.png)
