### ISSUE TITLE
关于历史操作target的标准制定

### ISSUE THREAD

**Issue by hanerx** [guateam/Intelligent-annotation-system#15]
**添加功能的初衷（问题）**
 在推荐文章的过程中发现需要约定target的标准后才能继续进行数据收集，并且在issue #8 中未详细指定，故需要讨论

**推荐解决方案**
target字段存储目标id

**备用解决方案**
target字段存储url，数据收集时处理字段

**截至日期**
未定

**Comment by laipz8200** [comment]
按我之前的想法数据库中的ID是代码+数字形式，这样就可以很方便的判断一个ID是用户还是文章还是评论等等，现在改成数字的话最好多加一个type来约束吧

**Comment by hanerx** [comment]
之前不是有type吗

**Comment by hanerx** [comment]
现在就在target里标记id了，到时候具体不同type的操作target可以设置成不同的数据

**Comment by laipz8200** [comment]
甚至想给不同type创建view

发自我的 iPhone
