### ISSUE TITLE
关于百科注释的访问

### ISSUE THREAD

**Issue by hanerx** [guateam/Intelligent-annotation-system#17]
**添加功能的初衷（问题）**
去查了一下百度的接口发现不能用，但是隔壁wiki的好像是可以的，所以开个issue讨论一下用wiki

**推荐解决方案**
https://www.cnblogs.com/zczhangcui/p/6251604.html
好处是改一点就能用

**备用解决方案**
`"https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch="+keyword+"&prop=info&inprop=url&utf8=&format=json"`
这个是网上找的接口，不过返回的不是直接的页面返回一个json文件
![image](https://user-images.githubusercontent.com/31791623/47651193-7ef3aa00-dbbd-11e8-9ced-e894189b07b7.png)
好处是好像高端一点

**备用解决方案2**
自己写wiki的api接口
https://www.mediawiki.org/wiki/API:Main_page/zh
好处是可以知道原理

**附加背景**
附加背景

**Comment by laipz8200** [comment]
wiki的能正常访问吗……

发自我的 iPhone

**Comment by hanerx** [comment]
百度的又不能正常访问，难不成访问萌娘百科啊

**Comment by laipz8200** [comment]
之后我看看有没有办法用爬虫做一个

发自我的 iPhone

**Comment by hanerx** [comment]
![iqtp 1k l z n 4v8ej 4](https://user-images.githubusercontent.com/31791623/47654832-a4d17c80-dbc6-11e8-9dc2-dd0d061fb8c6.jpg)爬百度。。。你认真的嘛

**Comment by laipz8200** [comment]
一个根据关键字获取内容的小接口应该还是可以的

发自我的 iPhone

**Comment by laipz8200** [comment]
已解决
