### ISSUE TITLE
添加点赞、收藏、不感兴趣和历史纪录的数据表

### ISSUE THREAD

**Issue by hanerx** [guateam/Intelligent-annotation-system#2]
**添加功能的初衷（问题）**
CF算法需要评分矩阵，并且主页需要显示点赞量和收藏量，但是数据库并没有相关数据

**推荐解决方案**
添加点赞收藏不感兴趣的数据表

| Column         | Datatype  | PrimaryKey | NotNull | Default           | Comments     | Extra       |
| -------------- | --------- | ---------- | ------- | ----------------- | ------------ | ----------- |
| id             | int(11)   | yes        | yes     | AI                | id       |             |
| article_id     | int(11)   | no         | yes     |                   | 文章id       | foreign key |
| user_id        | int(11)   | no         | yes     |                   | 用户id     | foreign key |
| type             | int(2)   | no        | yes     |                 | 操作种类（如果建多个表就不需要）       |             |

**Comment by laipz8200** [comment]
数据库结构有些不清晰，直接重构吧，找时间一起讨论一下方案

**Comment by hanerx** [comment]
![eer](https://user-images.githubusercontent.com/31791623/46396651-9062a700-c722-11e8-8563-fee0c3c6360d.png)
现在暂时改成这样，可能以后还要重构数据库

**Comment by hanerx** [comment]
![eer](https://user-images.githubusercontent.com/31791623/46398261-357f7e80-c727-11e8-82cf-a88aa13817bd.png)
介于后期可能需要用户行为分析，故将行为表整合为user_history
