### ISSUE TITLE
针对cf算法与文章分类的接口调整

### ISSUE THREAD

**Issue by hanerx** [guateam/Intelligent-annotation-system#3]
**添加功能的初衷（问题）**
为了适应新的数据库结构，需要将cf算法的接口进行修改

**接口修改后的格式**
1. 针对文章推荐的接口
  - 传入 用户的画像、数据库中的其他用户画像、需求返回标签量
  - 返回标签列表
2. 针对标签推荐的接口
  - 传入 用户画像、数据库中的其他用户画像、需求返回标签量
  - 返回标签列表
3. 针对文章分类的接口
  - 传入文章
  - 返回各标签的权重

**Comment by hanerx** [comment]
关于用户画像的存储方式我们还需要讨论一下
现在的设想是直接把各项权重放在一个字段里用“,”隔开这样
还有文章是不是需要itemcf算法来推荐

**Comment by laipz8200** [comment]
> 关于用户画像的存储方式我们还需要讨论一下
> 现在的设想是直接把各项权重放在一个字段里用“,”隔开这样
> 还有文章是不是需要itemcf算法来推荐

用户画像是向量形式，可以存在一个字段里的

**Comment by hanerx** [comment]
**关于我的设想备忘录**
- 文章提取类似高频词汇或中心词作为tag
- 文章的各类相似度用于Item CF算法
- 结合多种算法进行推荐

**Comment by hanerx** [comment]
![default](https://user-images.githubusercontent.com/31791623/46594105-9cc07880-cb03-11e8-99d7-f22f4e1d8bd3.png)
关于推荐系统的算法逻辑图

**Comment by MintCoffeeCat** [comment]
相似度矩阵计算出来之后需要保存在某处吗？

**Comment by MintCoffeeCat** [comment]
感觉存在数据库里面不太方便，可以存在文件里面。当文章和用户规模增大后，更新相似度矩阵的时机也是一个问题。是每次增加规模的时候更新，还是定期更新呢？

**Comment by laipz8200** [comment]
定期更新好些吧，每晚跑一遍之类的

发自我的 iPhone

**Comment by hanerx** [comment]
> 定期更新好些吧，每晚跑一遍之类的 发自我的 iPhone
> […](#)
> 在 2018年10月8日，下午2:35，smhhyyz ***@***.***> 写道： 感觉存在数据库里面不太方便，可以存在文件里面。当文章和用户规模增大后，更新相似度矩阵的时机也是一个问题。是每次增加规模的时候更新，还是定期更新呢？ — You are receiving this because you were assigned. Reply to this email directly, view it on GitHub, or mute the thread.

那新建一个文件夹保存自动更新的代码吗

**Comment by laipz8200** [comment]
先把操作更新的代码写好吧，控制的可以之后加进去

发自我的 iPhone

**Comment by hanerx** [comment]
![image](https://user-images.githubusercontent.com/31791623/46720467-2e1a2100-cca3-11e8-8494-ff6f0f931733.png)
暂时ITEMCF可以进行推荐了
