### ISSUE TITLE
关于用户画像的建表请求

### ISSUE THREAD

**Issue by hanerx** [guateam/Intelligent-annotation-system#5]
**添加功能的初衷（问题）**
由于yyz的CF算法输入是一维对所有文章的矩阵，请求添加用户画像表以存储用户画像
![image](https://user-images.githubusercontent.com/31791623/46594373-3e949500-cb05-11e8-8c5d-e25e91f665e9.png)

**推荐解决方案**
新建user_personas

| Field    | Type         | Null | Key  | Default           | Extra              |
| -------- | ------------ | ---- | ---- | ----------------- | ------------------ |
|id|INT | NO |  PRI  | NULL | auto_increment，id |
|article_id|INT | NO   |  | NULL | 文章id，Foreign Key |
|user_id|INT | NO   |  | NULL | 用户id，Foreign Key |
|weight|float | NO   |  | NULL | 权重 |

**备用解决方案**
将所有矩阵数据存入单个字段中，可能会很长

**Comment by laipz8200** [comment]
权重存放数字还是向量？

发自我的 iPhone

**Comment by MintCoffeeCat** [comment]
张煜这个表里的权重的意思就是评分，是到时候直接放在输入的评分矩阵里面的数值
![image](https://user-images.githubusercontent.com/37468676/46594980-ba441100-cb08-11e8-81f9-2ab52e624ffa.png)
按照这个来看的话，不同的用户行为需要赋予不同的权重，之后综合计算出一个数值，存到这个表里面的“权重”字段

**Comment by laipz8200** [comment]
画像表已建，删除了原先的database.sql
readme也换成了新的，但是前端的内容还是没加进去，所以旧版本保留了

**Comment by hanerx** [comment]
也就是说能用了是吧
