### ISSUE TITLE
优秀批注的算法讨论

### ISSUE THREAD

**Issue by hanerx** [guateam/Intelligent-annotation-system#7]
**添加功能的初衷（问题）**
对于推荐优秀批注的评定标准与讨论

**Comment by hanerx** [comment]
现在剩下的接口都是需要批注算法讨论的，需要赶紧把这个算法讨论一下![t01jkpmibji zva 8beo q](https://user-images.githubusercontent.com/31791623/46913863-05a66580-cfc8-11e8-9321-98bc16cdeef8.jpg)

**Comment by MintCoffeeCat** [comment]
可以尝试再用一下cf算法推荐批注

**Comment by hanerx** [comment]
用cf算法的话要讨论一下评分矩阵，代码的话可以直接用之前文章推荐的代码

**Comment by hanerx** [comment]
发现如果批注也使用cf算法的话，需要再建一个user_personas_postil的表，不然没办法放用户信息。
当场计算的话太慢了，所以重开话题申请建表

**Comment by hanerx** [comment]
现在的解决方案是新建了一张表user_personas_postil

| Field     | Type    | Null | Key  | Default | Extra               |
| --------- | ------- | ---- | ---- | ------- | ------------------- |
| id        | int(11) | NO   | PRI  | NULL    | auto_increment,id   |
| postil_id | int(11) | NO   | MUL  | NULL    | 批注id，Foreign Key |
| user_id   | int(11) | NO   | MUL  | NULL    | 用户id，Foreign Key |
| weight    | float   | NO   |      | NULL    | 权重                |

**Comment by hanerx** [comment]
按照这个思路现在暂时把批注推荐写了，先关issue了
