### ISSUE TITLE
关于用户历史纪录user_history表的type规定讨论

### ISSUE THREAD

**Issue by hanerx** [guateam/Intelligent-annotation-system#8]
**添加功能的初衷（问题）**
在编写推荐接口的过程中需要统计点赞与收藏数量，需要规定type的定义

**推荐解决方案**
![tim 20181008174815](https://user-images.githubusercontent.com/31791623/46602313-5fb7ae80-cb22-11e8-8f47-1e7a8a0d8019.jpg)
可能需要在这基础上继续添加部分规则

**Comment by hanerx** [comment]
关于用户浏览时间应该怎么计算？

**Comment by MintCoffeeCat** [comment]
浏览时间不要了

**Comment by hanerx** [comment]
那就按照原来的标准执行

| 代码 | 说明     | 备注           |
| ---- | -------- | -------------- |
| 0    | 取消     | 清除评论等工作 |
| 1    | 点击     |                |
| 2    | 阅读     |                |
| 3    | 收藏     |                |
| 4    | 点赞     |                |
| 5    | 点踩     |                |
| 6    | 关注     |                |
| 7    | 加入班级 |                |
| 8    | 上传文章 |                |
| 9    | 添加评论 |                |
| 10   | 添加批注 |                |
